/**
 * Runtime Generator
 * Converts AppSpec IR → actual executable code artifacts.
 * 
 * Generates:
 *   generated/pages/          → Next.js page components
 *   generated/api/            → Express route files
 *   generated/prisma/         → Prisma schema
 *   generated/auth/           → Auth middleware
 * 
 * Then the Simulator validates all generated artifacts.
 */

import { toSnakePlural } from '../types/appSpec.js';
import fs from 'fs';
import path from 'path';

// ── Main entry ────────────────────────────────────────────────────────────────

export function generateArtifacts(appSpec) {
  const artifacts = {};

  artifacts['prisma/schema.prisma'] = generatePrismaSchema(appSpec);
  artifacts['api/routes.js'] = generateAPIRoutes(appSpec);
  artifacts['auth/middleware.js'] = generateAuthMiddleware(appSpec);
  artifacts['pages/index.js'] = generatePageManifest(appSpec);

  for (const page of appSpec.pages) {
    artifacts[`pages/${page.name.toLowerCase()}.jsx`] = generatePageComponent(page, appSpec);
  }

  for (const entity of appSpec.entities) {
  artifacts[`api/${entity.name.toLowerCase()}Router.js`] =
      generateEntityRouter(entity, appSpec);
}


// ── Persist generated artifacts ─────────────────────

const outputDir='./generated';

if(!fs.existsSync(outputDir)){

    fs.mkdirSync(
        outputDir,
        {recursive:true}
    );
}

for(
    const [file,content]
    of Object.entries(artifacts)
){

    const filePath=
        path.join(
            outputDir,
            file
        );

    const directory=
        path.dirname(
            filePath
        );

    fs.mkdirSync(
        directory,
        {recursive:true}
    );

    fs.writeFileSync(
        filePath,
        content
    );
}

  return artifacts;
}

// ── Prisma Schema Generator ───────────────────────────────────────────────────

function generatePrismaSchema(appSpec) {
  const models = appSpec.entities.map(entity => {
    const fields = [
      `  id        String   @id @default(uuid())`,
      ...entity.fields.map(f => {
        const prismaType = fieldTypeToPrisma(f.type);
        const optional = !f.required ? '?' : '';
        const unique = f.unique ? ' @unique' : '';
        const defaultVal = f.type === 'boolean' ? ' @default(false)' : '';
        return `  ${f.name.padEnd(12)}${prismaType}${optional}${unique}${defaultVal}`;
      }),
      ...entity.relations.map(r => {
        if (r.type === 'belongsTo') {
          const fk = r.foreignKey || `${r.entity.toLowerCase()}Id`;
          return `  ${r.entity.toLowerCase().padEnd(12)}${r.entity}  @relation(fields: [${fk}], references: [id])\n  ${fk.padEnd(12)}String`;
        }
        if (r.type === 'hasMany') {
          return `  ${(r.entity.toLowerCase() + 's').padEnd(12)}${r.entity}[]`;
        }
        return `  // ${r.type} ${r.entity}`;
      }),
    ];

    if (entity.timestamps) {
      fields.push(`  createdAt DateTime @default(now())`);
      fields.push(`  updatedAt DateTime @updatedAt`);
    }
    if (entity.softDelete) {
      fields.push(`  deletedAt DateTime?`);
    }

    return `model ${entity.name} {\n${fields.join('\n')}\n}`;
  });

  // Always add User model if auth required
  const hasUser = appSpec.entities.some(e => e.name.toLowerCase() === 'user');
  if (!hasUser) {
    const roleEnum = appSpec.roles.map(r => r.name).join(', ');
    models.unshift(`enum Role {\n  ${appSpec.roles.map(r => r.name.toUpperCase()).join('\n  ')}\n}\n\nmodel User {\n  id           String   @id @default(uuid())\n  email        String   @unique\n  passwordHash String\n  role         Role     @default(${appSpec.roles.find(r => r.isDefault)?.name?.toUpperCase() || 'USER'})\n  createdAt    DateTime @default(now())\n  updatedAt    DateTime @updatedAt\n}`);
  }

  return `// Auto-generated by AppForge
// DO NOT EDIT MANUALLY

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${appSpec.auth?.strategy === 'session' ? 'sqlite' : 'postgresql'}"
  url      = env("DATABASE_URL")
}

${models.join('\n\n')}
`;
}

// ── API Routes Generator ──────────────────────────────────────────────────────

function generateAPIRoutes(appSpec) {
  const imports = appSpec.entities.map(e =>
    `import ${e.name.toLowerCase()}Router from './${e.name.toLowerCase()}Router.js';`
  ).join('\n');

  const mounts = appSpec.entities.map(e =>
    `router.use('/${toSnakePlural(e.name)}', ${e.name.toLowerCase()}Router);`
  ).join('\n');

  const authRoutes = appSpec.auth ? `
// Auth routes
router.post('/auth/register', async (req, res) => {
  const { email, password } = req.body;
  if (!email || !password) return res.status(400).json({ error: 'Email and password required' });
  // TODO: hash password, create user
  res.status(201).json({ message: 'User created' });
});

router.post('/auth/login', async (req, res) => {
  const { email, password } = req.body;
  // TODO: verify credentials, issue JWT
  res.json({ token: 'jwt_token_here', user: { email } });
});

router.get('/auth/me', authenticate, async (req, res) => {
  res.json({ user: req.user });
});
` : '';

  return `// Auto-generated by AppForge
import express from 'express';
import { PrismaClient } from '@prisma/client';
import { authenticate, authorize } from '../auth/middleware.js';

const prisma=new PrismaClient();
${imports}

const router = express.Router();
${authRoutes}
${mounts}

export default router;
`;
}

// ── Entity Router Generator ───────────────────────────────────────────────────

function generateEntityRouter(entity, appSpec) {
  const entityName = entity.name;
  const varName = entityName.toLowerCase();
  const tableName = entity.tableName;

  // Find endpoints for this entity
  const entityEndpoints = appSpec.endpoints.filter(ep => ep.entity === entityName);
  const hasRoleGuard = (ep) => ep.roles?.length > 0 ? `authorize(${JSON.stringify(ep.roles)})` : null;

  const routes = entityEndpoints.length > 0
    ? entityEndpoints.map(ep => {
        const method = ep.method.toLowerCase();
        const path =
  ep.path.replace(
      new RegExp(`.*\\/${tableName}\\/?`),
      '/'
  ) || '/';
        const guards = [ep.auth ? 'authenticate' : null, hasRoleGuard(ep)].filter(Boolean).join(', ');
        const guardsStr = guards ? `${guards}, ` : '';

        return `
// ${ep.description}
router.${method}('${path}', ${guardsStr}async (req, res) => {
  try {
    // TODO: implement with Prisma
    // const result = await prisma.${varName}.${ep.operation === 'list' ? 'findMany' : ep.operation === 'get' ? 'findUnique' : ep.operation}({ ... });
    res.json({ message: '${ep.description}', success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});`;
      }).join('\n')
    : `
// CRUD for ${entityName}
router.get('/', authenticate, async (req,res)=>{

  try{

    const items=
      await prisma.${varName}.findMany();

    res.json({
      items,
      total:items.length
    });

  }catch(err){

    res.status(500).json({
      error:err.message
    });

  }

});

router.post('/', authenticate, async(req,res)=>{

  try{

    const created=
      await prisma.${varName}.create({
          data:req.body
      });

    res.status(201).json(created);

  }catch(err){

      res.status(500).json({
          error:err.message
      });

  }

});

router.get('/:id', authenticate, async(req,res)=>{

  try{

      const item=
        await prisma.${varName}.findUnique({
            where:{
                id:req.params.id
            }
        });

      res.json(item);

  }catch(err){

      res.status(500).json({
          error:err.message
      });

  }

});

router.put('/:id', authenticate, async(req,res)=>{

 try{

      const updated=
        await prisma.${varName}.update({

            where:{
                id:req.params.id
            },

            data:req.body

        });

      res.json(updated);

 }catch(err){

      res.status(500).json({
          error:err.message
      });

 }

});

router.delete('/:id', authenticate, async(req,res)=>{

 try{

      await prisma.${varName}.delete({

          where:{
              id:req.params.id
          }

      });

      res.json({
          success:true
      });

 }catch(err){

      res.status(500).json({
          error:err.message
      });

 }

});`;

  return `// Auto-generated by AppForge — ${entityName} router
import express from 'express';
import { authenticate, authorize } from '../auth/middleware.js';

const router = express.Router();
${routes}

export default router;
`;
}

// ── Auth Middleware Generator ─────────────────────────────────────────────────

function generateAuthMiddleware(appSpec) {
  const strategy = appSpec.auth?.strategy || 'jwt';
  const jwtExpiry = appSpec.auth?.jwtConfig?.expiry || '7d';
  const roles = appSpec.roles.map(r => r.name);

  return `// Auto-generated by AppForge — Auth Middleware
// Strategy: ${strategy}
import jwt from 'jsonwebtoken';

const JWT_SECRET = process.env.JWT_SECRET || 'change_me_in_production';
const VALID_ROLES = ${JSON.stringify(roles)};

export function authenticate(req, res, next) {
  const header = req.headers['authorization'];
  if (!header || !header.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Authentication required' });
  }
  const token = header.slice(7);
  try {
    const payload = jwt.verify(token, JWT_SECRET);
    req.user = payload;
    next();
  } catch {
    return res.status(401).json({ error: 'Invalid or expired token' });
  }
}

export function authorize(...allowedRoles) {
  return (req, res, next) => {
    if (!req.user) return res.status(401).json({ error: 'Not authenticated' });
    if (!allowedRoles.includes(req.user.role)) {
      return res.status(403).json({ error: \`Requires role: \${allowedRoles.join(' or ')}\` });
    }
    next();
  };
}

export function generateToken(user) {
  return jwt.sign(
    { id: user.id, email: user.email, role: user.role },
    JWT_SECRET,
    { expiresIn: '${jwtExpiry}', algorithm: '${appSpec.auth?.jwtConfig?.algorithm || 'HS256'}' }
  );
}
`;
}

// ── Page Component Generator ──────────────────────────────────────────────────

function generatePageComponent(page, appSpec) {
  const hasForm = page.sections?.some(s => s.type === 'form');
  const hasTable = page.sections?.some(s => s.type === 'table');

  return `// Auto-generated by AppForge — ${page.name} page
// Route: ${page.route}
// Layout: ${page.layout}
// Protected: ${page.protected}${page.roles?.length ? ` | Roles: ${page.roles.join(', ')}` : ''}

import { useState, useEffect } from 'react';

export default function ${page.name}Page() {
${hasForm ? `  const [formData, setFormData] = useState({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      // TODO: call API
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };` : ''}
${hasTable ? `  const [items, setItems] = useState([]);
  
  useEffect(() => {
    // TODO: fetch data from API
    fetch('${appSpec.apiConfig?.baseUrl || '/api/v1'}${page.route}')
      .then(r => r.json())
      .then(data => setItems(data.items || []));
  }, []);` : ''}

  return (

<div className="${page.layout}-layout space-y-6">

<h1 className="text-3xl font-bold">
${page.title}
</h1>

${hasTable ? `
<div className="border rounded p-4">

<h2 className="font-semibold">
Data Table
</h2>

{items.length===0
? <p>No records found</p>
: <ul>
{items.map(item=>(
<li key={item.id}>
{JSON.stringify(item)}
</li>
))}
</ul>
}

</div>
` : ''}

${hasForm ? `
<form
onSubmit={handleSubmit}
className="border rounded p-4"
>

<input
placeholder="Enter value"
className="border p-2"
/>

<button
type="submit"
>
Submit
</button>

</form>
` : ''}

</div>

);
}

// Route config
export const routeConfig = {
  path: '${page.route}',
  protected: ${page.protected},
  roles: ${JSON.stringify(page.roles || [])},
};
`;
}

// ── Page Manifest ─────────────────────────────────────────────────────────────

function generatePageManifest(appSpec) {
  const imports = appSpec.pages.map(p =>
    `import ${p.name}Page from './${p.name.toLowerCase()}.jsx';`
  ).join('\n');

  const routes = appSpec.pages.map(p =>
    `  { path: '${p.route}', component: ${p.name}Page, protected: ${p.protected}, roles: ${JSON.stringify(p.roles || [])} },`
  ).join('\n');

  return `// Auto-generated by AppForge — Page manifest
${imports}

export const routes = [
${routes}
];

export default routes;
`;
}

// ── Type helpers ─────────────────────────────────────────────────────────────

function fieldTypeToPrisma(type) {
  const map = {
    string: 'String', number: 'Int', boolean: 'Boolean',
    date: 'DateTime', email: 'String', enum: 'String',
    uuid: 'String', text: 'String', json: 'Json',
    decimal: 'Decimal', password: 'String',
  };
  return map[type] || 'String';
}
